#Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuração do H2
spring:
  flyway:
    enabled: false
    cleanDisabled: true
    create-schemas: true
    url: jdbc:postgresql://localhost:5432/localdb
    user: postgres
    password: postgres
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jakarta.persistence.schema-generation.scripts:
        action: drop-and-create
        create-source: metadata
        create-target: target/create.sql
        drop-source: metadata
        drop-target: target/drop.sql
  # Configuração do Keycloak + security
security:
  oauth2:
    client:
      registration:
        keycloak:
          client-id: biblioteca-api
          client-secret:
          scope: openid, profile, email
    provider:
      keycloak:
        issuer-uri: http://localhost:8280/auth/realms/biblioteca
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8280/realms/biblioteca
keycloak:
  auth-server-url: http://localhost:8280
  realm: biblioteca
  resource: biblioteca-api
  credentials:
    ssl-required: external
    bearer-only: true
    use-resource-role-mappings: true

#swagger + openapi
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

openapi:
  title: API de Gerenciamento de Biblioteca
  description: API para gerenciamento de biblioteca
  version: 1.0.0
  contact:
    name: RSDesenvolvimento
    url: https://rsdesenvolvimento.com.br
    email: rsdesenvolvimento@gmail.com
  license:
    name: Apache License 2.0

# configurações de logging
logging:
  level:
    com.amazonaws: error
    org:
      flywaydb: info
      hibernate: info
      hibernate.SQL: debug
      hibernate.orm.jdbc.bind: trace
      hibernate.boot.internal: error
      # hibernate.stat: debug
      # hibernate.SQL_SLOW: info
      hibernate.envers: error
      hibernate.cache: info
      ehcache: info
      springframework:
        web:
          debug
          # filter: debug
          # client: debug
        jdbc.core:
          JdbcTemplate: debug
          StatementCreatorUtils: trace
        transaction: error
        security: error
      keycloak: error

# configuração da aplicação
app:
  time-zone: America/Belem
  locale: pt_BR
  base-url: http://localhost:8080
