#Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuração do H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa # Usuário padrão do H2
    password: "" # Senha vazia por padrão
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuração do Keycloak + security
security:
  oauth2:
    client:
      registration:
        keycloak:
          client-id: biblioteca-api
          client-secret:
          provider: keycloak
          authorization-grant-type: authorization_code
keycloak:
  auth-server-url: http://localhost:8080/realms/biblioteca
  realm: biblioteca
  resource: biblioteca-api
  credentials:
    secret: YOUR_CLIENT_SECRET
  principal-attribute: preferred_username

#swagger + openapi
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

openapi:
  title: API de Gerenciamento de Biblioteca
  description: API para gerenciamento de biblioteca
  version: 1.0.0
  contact:
    name: RSDesenvolvimento
    url: https://rsdesenvolvimento.com.br
    email: rsdesenvolvimento@gmail.com
  license:
    name: Apache License 2.0

# configurações de logging
logging:
  level:
    com.amazonaws: error
    org:
      flywaydb: info
      hibernate: info
      hibernate.SQL: debug
      hibernate.orm.jdbc.bind: trace
      hibernate.boot.internal: error
      # hibernate.stat: debug
      # hibernate.SQL_SLOW: info
      hibernate.envers: error
      hibernate.cache: info
      ehcache: info
      springframework:
        web:
          debug
          # filter: debug
          # client: debug
        jdbc.core:
          JdbcTemplate: debug
          StatementCreatorUtils: trace
        transaction: error
        security: error
      keycloak: error

# configuração da aplicação
app:
  time-zone: America/Belem
  locale: pt_BR
  base-url: http://localhost:8080
