#Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: Biblioteca Baseline
    create-schemas: ${FLYWAY_CREATE_SCHEMA:true}
    default-schema: ${FLYWAY_DEFAULT_SCHEMA:biblioteca_adm}
    schemas: ${FLYWAY_SCHEMAS:biblioteca}
    # cleanDisabled: true
    # create-schemas: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/localdb}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    # locations: ${FLYWAY_LOCATIONS:classpath:db/migration,filesystem:/tmp/import/V0}
    locations: ${FLYWAY_LOCATIONS:filesystem:/tmp/import/V0}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/localdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_SHOW_SQL:true}
      jakarta.persistence.schema-generation.scripts:
        action: none
        # create-source: metadata
        # create-target: target/create.sql
        # drop-source: metadata
        # drop-target: target/drop.sql
  sql:
    init:
      mode: never
  # Configuração do Keycloak + security
security:
  enabled: false
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${OAUTH_RESOURCESERVER_JWT:http://localhost:8280/auth/realms/REALM_LOCAL/protocol/openid-connect/certs}

#swagger + openapi
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

openapi:
  title: API de Gerenciamento de Biblioteca
  description: API para gerenciamento de biblioteca
  version: 1.0.0
  contact:
    name: RSDesenvolvimento
    url: https://rsdesenvolvimento.com.br
    email: rsdesenvolvimento@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  resource: ${OAUTH_CLIENT_ID:biblioteca-ui}

# configurações de logging
logging:
  level:
    org:
      flywaydb: info
      hibernate: info
      hibernate.SQL: debug
      hibernate.orm.jdbc.bind: trace
      hibernate.boot.internal: error
      # hibernate.stat: debug
      # hibernate.SQL_SLOW: info
      hibernate.envers: error
      hibernate.cache: info
      ehcache: info
      springframework:
        web:
          debug
          # filter: debug
          # client: debug
        jdbc.core:
          JdbcTemplate: debug
          StatementCreatorUtils: trace
        transaction: error
        security: error
      keycloak: error

# configuração da aplicação
app:
  time-zone: America/Belem
  locale: pt_BR
  base-url: http://localhost:8080
