version: "3"
services:
  postgres-local:
    image: postgres
    container_name: postgres-local
    volumes:
      - ./infra/postgres/scripts:/docker-entrypoint-initdb.d
      - ./.app/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_EXTRA_SCHEMAS: keycloak,srh2
      POSTGRES_DB: localdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    networks:
      - local-network

  keycloak-local:
    image: bitnami/keycloak:19.0.3
    container_name: keycloak-local
    volumes:
      - ./infra/keycloak/import:/import
      - ./infra/keycloak/scripts:/docker-entrypoint-initdb.d
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres-local
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: localdb
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_DATABASE_SCHEMA: keycloak
      KEYCLOAK_LOG_LEVEL: error
      KEYCLOAK_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile.feature.scripts=enabled
    ports:
      - "8280:8080"
    depends_on:
      postgres-local:
        condition: service_healthy
    networks:
      - local-network

  biblioteca-api-local:
    container_name: biblioteca-api-local
    environment:
      AMBIENTE: Local
      BASE_URL: http://localhost:8080
      API_URL: http://localhost:8080/api

      DEFAULT_TIMEZONE: America/Belem
      DEFAULT_LOCALE: pt-BR
      LOGGING_LEVEL: debug

      DB_DRIVER_CLASS_NAME: org.postgresql.Driver
      JPA_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_URL: jdbc:postgresql://postgres-local:5432/localdb
      DB_SCHEMA: biblioteca
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JPA_SHOW_SQL: true
      ENABLE_CACHE: true

      FLYWAY_ENABLED: true
      FLYWAY_CREATE_SCHEMA: true
      FLYWAY_DEFAULT_SCHEMA: biblioteca_adm
      FLYWAY_SCHEMAS: biblioteca,biblioteca_adm
      FLYWAY_LOCATIONS: filesystem:/tmp/import

      OAUTH_RESOURCESERVER_JWT: http://keycloak-local:8080/auth/realms/REALM_LOCAL/protocol/openid-connect/certs
      OAUTH_CLIENT_ID: biblioteca-ui

    ports:
      - "8080:8080"
    volumes:
      - ./infra/biblioteca/api/db:/tmp/import
    depends_on:
      postgres-local:
        condition: service_healthy
    networks:
      - local-network

  biblioteca-ui-local:
    container_name: biblioteca-ui-local
    environment:
      IMAGE_VERSION: <PROJECT_VERSION>
      AMBIENTE: Local
      BASE_URL: http://localhost:8080
      API_URL: http://localhost:8080/api

      DEFAULT_TIMEZONE: America/Belem
      DEFAULT_LOCALE: pt-BR
      LOGGING_LEVEL: debug

      OAUTH_ISSUER: http://localhost:8280/auth/realms/REALM_LOCAL
      OAUTH_CLIENT_ID: biblioteca-ui

      REQUIRE_HTTPS: false
    ports:
      - "4200:80"
    depends_on:
      - integracoes-keycloak-local
      - biblioteca-api-local
    networks:
      - local-network
networks:
  local-network:
    name: local-network
